### ISSUE TITLE
Execution failed for task ':app:minifyGoogleDebugWithR8' V1.2.9

### ISSUE THREAD

**Issue by tiansuo** [koral--/android-gif-drawable#856]
I have this error after update to v1.2.9,with 1.2.8,it‘s fine

AGPBI: {"kind":"error","text":"java.lang.NullPointerException","sources":[{"file":"C:\\Users\\Administrator\\.gradle\\caches\\transforms-3\\19768f2aac56d37ee5f8f06365cc4a7a\\transformed\\jetified-android-gif-drawable-1.2.29-runtime.jar"}],"tool":"R8"}

* What went wrong:
Execution failed for task ':app:minifyBaiduDebugWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: C:\Users\Administrator\.gradle\caches\transforms-3\19768f2aac56d37ee5f8f06365cc4a7a\transformed\jetified-android-gif-drawable-1.2.29-runtime.jar:pl/droidsonroids/gif/GifAnimationMetaData$1.class

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:minifyBaiduDebugWithR8'

Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\Administrator\.gradle\caches\transforms-3\19768f2aac56d37ee5f8f06365cc4a7a\transformed\jetified-android-gif-drawable-1.2.29-runtime.jar:pl/droidsonroids/gif/GifAnimationMetaData$1.class
	at Version.fakeStackEntry(Version_4.0.52.java:0)

Caused by: java.lang.NullPointerException

**Comment by koral--** [comment]
Could you create and share a minimal reproducer project (which reproduces the issue but does not contain any confidential data)?

**Comment by koral--** [comment]
Closed due to inactivity

**Comment by biaji** [comment]
> I have this error after update to v1.2.9,with 1.2.8,it‘s fine
> 
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:minifyBaiduDebugWithR8'
> 
> Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\Administrator.gradle\caches\transforms-3\19768f2aac56d37ee5f8f06365cc4a7a\transformed\jetified-android-gif-drawable-1.2.29-runtime.jar:pl/droidsonroids/gif/GifAnimationMetaData$1.class at Version.fakeStackEntry(Version_4.0.52.java:0)
> 
> Caused by: java.lang.NullPointerException


Would you please share the build env?  I'm encounting the same issue:

```
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /app/build/intermediates/transforms/ajx/icenter/debug/103.jar:pl/droidsonroids/gif/GifAnimationMetaData$1.class
	at Version.fakeStackEntry(Version_4.0.52.java:0)
```

IDE: Android Studio Otter | 2025.2.1 Patch 1
AGP: 7.4.2

I'm trying to exclude this pkg from aspectjx,  keep updating.
